"""create assemblies table

Revision ID: 5d5e9dc25f81
Revises: 
Create Date: 2026-07-02 19:27:01.372151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5e9dc25f81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assemblies',
    sa.Column('accession', sa.String(), nullable=False),
    sa.Column('organism_name', sa.String(), nullable=False),
    sa.Column('tax_id', sa.Integer(), nullable=True),
    sa.Column('assembly_level', sa.String(), nullable=True),
    sa.Column('assembly_name', sa.String(), nullable=True),
    sa.Column('submitter', sa.String(), nullable=True),
    sa.Column('bioproject_accession', sa.String(), nullable=True),
    sa.Column('biosample_accession', sa.String(), nullable=True),
    sa.Column('contig_n50', sa.Integer(), nullable=True),
    sa.Column('total_sequence_length', sa.BigInteger(), nullable=True),
    sa.Column('number_of_contigs', sa.Integer(), nullable=True),
    sa.Column('gc_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('accession')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assemblies')
    # ### end Alembic commands ###
