"""add checkm and ani columns

Revision ID: 84a826d2733d
Revises: 5d5e9dc25f81
Create Date: 2026-07-04 15:15:52.445405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a826d2733d'
down_revision: Union[str, Sequence[str], None] = '5d5e9dc25f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assemblies', sa.Column('checkm_completeness', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('assemblies', sa.Column('checkm_contamination', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('assemblies', sa.Column('ani_best_match_organism', sa.String(), nullable=True))
    op.add_column('assemblies', sa.Column('ani_best_match_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assemblies', 'ani_best_match_percent')
    op.drop_column('assemblies', 'ani_best_match_organism')
    op.drop_column('assemblies', 'checkm_contamination')
    op.drop_column('assemblies', 'checkm_completeness')
    # ### end Alembic commands ###
