"""add species_tax_id column

Revision ID: c2aba1132a27
Revises: 84a826d2733d
Create Date: 2026-07-08 17:21:03.064276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2aba1132a27'
down_revision: Union[str, Sequence[str], None] = '84a826d2733d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assemblies', sa.Column('species_tax_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assemblies', 'species_tax_id')
    # ### end Alembic commands ###
